version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 8610:8610
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daikon0313
    volumes:
      - ./postgres:/var/lib/postgresql/data